FreeRDP/Remmina

- CMakeLists.txt
- remmina/CMakeLists.txt
The installation of the headers in `remmina/include/remmina` has been
broken ever since Remmina moved away from autotools, as the path
specified in the call to `install()` did not exist.
Move the `install()` call to remmina/ so that it works, and add a trailing
/ to the path so that we do not end up with `$CMAKE_INSTALL_PREFIX/include/remmina/remmina`.
> remmina: Actually install its headers.

- remmina-plugins/nx/nx_plugin.h
- remmina-plugins/nx/nx_session_manager.c
Fixes issue #16 make sessions in the NX session dialog double-clickable
> Handle double click on the NX session rows to activate the default response

- remmina/src/remmina_main.c
Fixes issue #250 Double-clicking a column header to sort list of saved connections actually attempts connection
> Moved the double click event and the enter buttons press in the row-activated signal handler

- remmina-plugins/nx/nx_session.c
- remmina/src/remmina_applet_menu_item.c
- remmina/src/remmina_external_tools.c
- remmina/src/remmina_file.c
- remmina/src/remmina_public.c
In some cases it doesn't look like Remmina will survive if these ever return NULL, however it's going to be needed eventually ;-)
> Fix small memory leaks and a NULL ptr dereference.

- remmina/src/remmina_file_editor.c
- remmina/src/remmina_pref_dialog.c
- remmina/src/remmina_public.c
- remmina/src/remmina_public.h
@muflone it works, but I'm not sure about the quality of the code. Can you please review it?
Thanks in advance
> Fixes FreeRDP/Remmina#473 - Customize button in the connection editor should  show the resolutions dialog

- remmina-plugins/vnc/vnc_plugin.c
VNC plugin uses GQueue to store events. GQueue is not threadsafe
and needs protection when accessed from different threads.
The problem may be reproduced on original code by opening vnc
connection and quickly scrolling up and down some window. Eventually
session locks. This patch addresses this issues?
Signed-off-by: Nikolay Martynov <mar.kolya@gmail.com>
> Fix race condition in VNC event queue

- remmina/CMakeLists.txt
- remmina/src/remmina_connection_window.c
- remmina/src/remmina_file_editor.c
- remmina/src/remmina_preexec.c
- remmina/src/remmina_preexec.h
- remmina/ui/CMakeLists.txt
- remmina/ui/remmina_spinner.glade
A command that can be executed just before any connection.
Fixes #553 , requested in the #520 issue by @BrainwreckedTech
Can you please test/destroy/critics and let me know?
@giox069
> Prior Connection Command

- remmina/src/remmina_ssh.c
I've added the support for ~/.ssh/config, but keep in mind that most of the ssh options are not supported by libssh , so I'm not sure it will works as you like, please test it.
I'm going to merge this in 'next'
> Support for ~/.ssh/config closes #235 , libssh does not support most of the ssh options

- remmina/src/remmina_preexec.c
It solves
> GLib-CRITICAL **: g_shell_quote: assertion 'unquoted_string != NULL' failed
> Exception when precommad in NULL. Reference #591

- remmina-plugins/rdp/rdp_plugin.c
Used for load balancing RDP sessions using an RDP broker.
> Filling out LoadBalanceInfo in the RDP settings struct

- remmina/desktop/CMakeLists.txt
- remmina/desktop/remmina.desktop.in
This patch makes sure that when remmina is started via the desktop
file it always starts the binary shipped with the distribution
and not another remmina binary that my have higher precedence
in the search path, such as in /usr/local/bin/.
Without this patch, if there is a remmina binary in /usr/local/bin, for example because the user previously compiled remmina, and then decided to go back to the distribution version, but the binary was not correctly cleaned up, then the .desktop file installed by the distribution will try to execute the binary in /usr/local/bin instead of /usr/bin, which can be a very annoying cause of errors.
With this patch, if the user installs both Remmina from the distribution and compiles a newer version by himself, then he will end up with to .desktop files, one …
> remmina.desktop: Use full path to execute remmina

- remmina/desktop/remmina.desktop.in
> fix regression introduced by 190ea2f98ab0443b8a05f70c79e2af037f9fca94

- remmina/include/remmina/plugin.h
- remmina/src/remmina_plugin_manager.c
- remmina/src/remmina_pref.c
- remmina/src/remmina_pref.h
- remmina/src/remmina_pref_dialog.c
- remmina/src/remmina_pref_dialog.h
- remmina/src/remmina_ssh.c
- remmina/ui/remmina_preferences.glade
This merge add a new option in remmina preferences to set the ssh log level.
This feature is useful to investigate #176 #331 #539 
@giox069 minor enhancements, it has been tested on fedora f21, f22, Arch Linux
> libssh fixes - SSH_OPTIONS_LOG_VERBOSITY

- remmina/include/remmina/plugin.h
- remmina/src/remmina_plugin_manager.c
- remmina/src/remmina_pref.c
- remmina/src/remmina_pref.h
- remmina/src/remmina_pref_dialog.c
- remmina/src/remmina_pref_dialog.h
- remmina/src/remmina_ssh.c
- remmina/ui/remmina_preferences.glade
Added preference 'ssh_parseconfig' to enable/disable parsing of ~/.ssh/config before establishing an SSH connection
> Makes parsing of ~/.ssh/config optional closes #648

- remmina/src/remmina.c
This is a temporary patch to disable wayland. It will be rolled back as soon as we will adapt remmina to work with wayland.
closes #677, closes #671, closes #672, closes #673, closes #674, closes #675, closes #676
> Disable wayland backend 

- remmina/ui/remmina_main.glade
Icons in the main window are bigger than their original size making the icons looks ugly.
> Reduce main window icons size fixes #701

- remmina-plugins/vnc/vnc_plugin.c
The vnc plugin uses the jpeg compression algorithm, that cannot works with an 8 bit color depth (256 colors).
This pull request temporarily remove the "256 Colors" color depth mode, to avoid new issues as reported by #699 
The 8 bit mode will be eventually fixed in a future release.
> Temporay fixes #699 - Set default color depth to 15 (high colors)

- remmina-plugins/tool_hello_world/plugin.c
- remmina/include/remmina/plugin.h
- remmina/src/remmina_applet_menu.c
- remmina/src/remmina_file.c
- remmina/src/remmina_file_manager.c
- remmina/src/remmina_file_manager.h
- remmina/src/remmina_plugin_manager.c
- remmina/src/remmina_survey.c
I've made the remmina user data dir (~/.remmina or ~/.local/share/remmina) a global variable, to avoid to call continuously the same code in all the function where is needed.
@giox069 can you please validate and if it's fine merge it? Thx
> XDG - make remmina user data dir global

- remmina/CMakeLists.txt
- remmina/src/remmina_connection_window.c
- remmina/src/remmina_file_editor.c
- remmina/src/remmina_plugin_cmdexec.c
- remmina/src/remmina_plugin_cmdexec.h
- remmina/src/remmina_protocol_widget.c
This patch provides a means to execute a command (or a script) just after a connection close. 
This complete and improve the #553 request
There are some minor issues that will be addressed in a following release, like arguments parsing.
> Feature Request: After Command #746

- remmina/src/remmina_main.c
After showing the remmina_file_editor dialog, the previous selected file is highlighted.
This PR closes #786
> Selected item is lost after editing a profile. Closes #786

- remmina/src/remmina_main.c
- remmina/ui/remmina_main.glade
This PR close #791
1. Underscore in Quick Find removed as reported by #791 
2. Refresh file list in the remmina main after adding a new entry
> Quickfind fixes - Close #791

- remmina-plugins/rdp/rdp_file.c
i had to manually add the loadbalanceinfo but it took my quite a while to figure out that that was the part which was missing...
> fix loadbalanceinfo in import

- AUTHORS
- THANKS.md
- remmina-plugins/rdp/rdp_plugin.c
- remmina/src/remmina.c
- remmina/src/remmina_connection_window.c
- remmina/src/remmina_exec.c
- remmina/src/remmina_masterthread_exec.c
- remmina/src/remmina_masterthread_exec.h
- remmina/src/remmina_pref.c
- remmina/src/remmina_ssh.c
- remmina/src/remmina_ssh_plugin.c
- remmina/src/remmina_ssh_plugin.h
- remmina/ui/remmina_about.glade
- remmina/ui/remmina_preferences.glade
This PR fixes issue #836, but also makes remmina compliant with GtkApplication object, converting commandline parsing as described in GApplication for GLib 2.40 and above.
Some minor fixes are included for correct screenshot creation.
> Screenshot segfault

- remmina-plugins/nx/nx_plugin.c
- remmina-plugins/xdmcp/xdmcp_plugin.c
- remmina/include/remmina/plugin.h
- remmina/src/remmina.c
- remmina/src/remmina_connection_window.c
- remmina/src/remmina_plugin_manager.c
- remmina/src/remmina_protocol_widget.c
- remmina/src/remmina_protocol_widget.h
Allow remmina to be run under native wayland.
Tested under Arch Gnome on Wayland, with
```
GDK_BACKEND=wayland remmina
```
- Plugins which use GtkSocket will report a correct error and will never be able to run
- Remmina still need to be linked to Xorg libraries for some extra functions (ie: keyboard mapping in RDP)
> Initial support for Wayland and Mir

- remmina-plugins/spice/spice_plugin.c
- remmina/src/remmina_main.c
Hi,
Here are more improvements for the SPICE plugin:
- Fix a memory leak for the SpiceSession,
- Run the authentication dialog if the password is wrong or missing,
- Add the SPICE protocol to the quick connect list.  
Regards.
> More SPICE plugin improvements

- remmina-plugins/spice/spice_plugin.c
- remmina/src/remmina_masterthread_exec.h
- remmina/src/remmina_public.c
The implementation has been taken from `spicy`.
Testing it on ArchLinux requires [this workaround](https://bbs.archlinux.org/viewtopic.php?id=210135) due to a [bug](https://bugs.archlinux.org/task/49179) in the latest version of the package `spice-gtk3`.
Could you test it on other distributions ?
> SPICE plugin: USB redirection support + minor fixes

- remmina/src/remmina_connection_window.c
When remote is bigger than local display window you can use `hostkey` + `<arrows>` to move the view-port to the edges of remote desktop. 
It works in both modes: 'fullscreen' an 'not fullscreen'.
P.S.
the README.md points to broken links for development installation, for example:
`Compile on Ubuntu 14.04 and 14.10` points to `blob/something` instead of `wiki/ ... `.
> add shortcuts to show remote desktop edges

- _config.yml
- docs/wiki/Compile-Remmina-on-Arch-Linux.md
- docs/wiki/Compile-on-Fedora-20.md
- docs/wiki/Compile-on-Ubuntu-14.04-and-14.10.asciidoc
- docs/wiki/Compile-on-Ubuntu-14.04.md
- docs/wiki/Compile-on-Ubuntu-16.04.md
- docs/wiki/Development-Notes.md
- docs/wiki/GTK-versions-on-various-distributions.md
- docs/wiki/HOWTO-generate-the-changelog.md
- docs/wiki/Home.md
- docs/wiki/How-to-compile-Remmina-on-FreeBSD.md
- docs/wiki/Remmina-Usage-FAQ.md
- docs/wiki/Remmina-User's-guide.md
- docs/wiki/Submodules.md
- docs/wiki/Systray-menu.md
- docs/wiki/Update-gettext-messages.md
- docs/wiki/_config.yml
Embed release-related documentation into git repository.
> Embed docs

- .travis.yml
libwebkit2gtk-3.0-dev is required to build Remmina on trusty via
cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON --build=build <src_dir>
Signed-off-by: Dmitrii Shcherbakov <fw.dmitrii at gmail.com>
> .travis.yml: Add a missing dependency

- remmina-plugins/rdp/rdp_plugin.c
- remmina-plugins/rdp/rdp_settings.c
- remmina-plugins/rdp/rdp_settings.h
This PR enables RDP server scaling in HiDPI display and screen orientation, and fixes #969.
Remote scaling and orientation are documented in [[MS-RDPBCGR] TS_UD_CS_CORE](https://msdn.microsoft.com/en-us/library/cc240510.aspx).
Settings are currently not automatically detected from your current monitor: you must manually enable them in remmina global setttings, RDP tab.
Orientation: can be 0, 90, 180, 270 degrees.
Desktop Scale Factor: scaling of desktop and desktop apps, range from 100% to 500%
Device Scale Factor: scaling of metro (appstore?) apps. Works on Win2012R2, windows 10 seems to ignore it. Can only be 100%, 140% or 180%.
> Implementing RDP remote scaling and orientation

- remmina-plugins/spice/CMakeLists.txt
- remmina-plugins/spice/spice_plugin.c
- remmina-plugins/spice/spice_plugin.h
- remmina-plugins/spice/spice_plugin_file_transfer.c
Please review and test:
- connect to a guest having `spice-vdagent` running,
- drag and drop files from the host to the guest,
- a dialog should raise with a progress bar (if files are too small, the dialog is closed promptly),
- after the transfer is completed, files can be find on the guest in `$XDG_DOWNLOAD_DIR ("$HOME/Downloads")`
> spice: show progress of drag & drop file transfers

- remmina/src/remmina_main.c
- remmina/ui/remmina_main.glade
This PR does nothing special than just adding an event when entering the quick search entry widget.
It shouldn't break up anything, but please test it if you can.
To test, just enter some text in the quick search, leave the box, with TAB for example and go back again with the S-TAB (with the mouse it won't work and it's normal).
> When focus-in inside the quick search, select the whole text as per #544

- remmina/src/remmina_applet_menu.c
- remmina/src/remmina_file.c
- remmina/src/remmina_file_manager.c
- remmina/src/remmina_file_manager.h
- remmina/src/remmina_plugin_manager.c
- remmina/src/remmina_pref.c
- remmina/src/remmina_survey.c
Added full support for XDG_DATA_DIRS and XDG_CONFIG_DIRS as requested by #818
To test you can move away your ~/.remmina, or ~/.config/remmina and ~/.local/share/remmina directories.
You can (manually at the moment), populate your $XDG_CONFIG_DIRS/remmina (it should be /etc/xdg/remmina) with your ~/.config/remmina/remmina.pref (and move away the ~/.config/remmina directory). Same for the .remmina files you have under ~/.local/share/remmina, that you can copy into $XDG_DATA_DIRS (normally /usr/share/remmina or /usr/local/share/remmina), again, removing the ~/.local/share/remmina directory.
As a last improvements I was thinking to add by default some template profiles to show up some different Remmina configurations in the XDG system directories.
I think there is still a big issue, but I …
> XDG base directory spec

- README.md
On Ubuntu below 16.04, libssh is still at version 0.6.X. This makes it impossible to connect to more securely configured SSH servers like shown in this bug issue: https://github.com/FreeRDP/Remmina/issues/983
This change helps people trying to figure out on how to connect to SSH servers using more secure algorithms which aren't supported by libssh 0.6.X.
> Show information on upgrade libssh to 0.7.X

- remmina/desktop/remmina.desktop.in
It allows to override the default "Quit" command in Unity launcher
Translations are not needed for this.
> remmina.desktop: add Quit desktop action for Unity

- remmina/src/remmina_connection_window.c
From my testing on a Fedora 25 (Gnome 3.22) system, it looks like placing the window in fullscreen from the idle callback is too soon and always places the window on monitor 0 (left one).
If gtk_window_fullscreen() is called from the "map-event" event, it places the window on the same monitor where the window was.
I didn't experience the black border issue mentioned in the previous comment. Using a signal instead of the idle callback means we don't need to track the event source identifier, which removes some code.
I'd be happy if somebody could test this on other environments (non Gnome, or pre-3.22 versions).
> Fix fullscreen window position (#873)

- remmina-plugins/rdp/rdp_plugin.c
- remmina/po/it.po
@antenore: I added 4 new text strings for these errors. Can you have them reviewed by a English mother tongue technician ?
> Add descriptions for some freerdp exit status code

- remmina-plugins/rdp/rdp_event.c
- remmina/po/de.po
Fixes a bad format string in the german translation which caused a crash, see issue #1080. Also fixes a small memory leak.
> Fix german translation

- remmina/src/remmina_connection_window.c
- remmina/src/remmina_pref.c
- remmina/src/remmina_pref.h
- remmina/src/remmina_pref_dialog.c
- remmina/src/remmina_pref_dialog.h
- remmina/ui/remmina_preferences.glade
Added an option to completely disable the floating toolbar in fullscreen mode.  This is useful for people like me who use Remmina like a thin client.
The floating toolbar interferes in a Windows RDP session when you bring the cursor to the top (I exit the session by accident all the time), and if you move it to the bottom, it interferes with the Windows taskbar.
I'm not very familiar with the Remmina code base, so please let me know if there's a better way to do something.  I tried to pattern my changes after your existing code.
By the way - thanks for a great product!  Remmina has been very handy over the years!!
> Add an option to completely disable the floating toolbar in fullscreen mode

- remmina-plugins/rdp/rdp_plugin.c
This PR add the server name to the "Another user connected to the server, forcing the disconnection of the current connection." error message as requested by @CS-JS  (issue #1141 )
> Add server name to popup warning

- snap/snapcraft.yaml.in
This allows also to generate various .cache at snaping time.
Using a version that supports getpw properly in order to fix the
SSH connection issue.
Fixes #1129
> snapcraft: use snap-preload to get dynamic access to /snap path

- remmina/src/remmina_init_dialog.c
In the authentication dialog where the user name, password and domain are entered, currently the dialog is submitted by pressing the Enter key only in the password entry. With this modification, pressing the Enter key in the domain entry submits the dialog, too. Since the domain entry is the last entry of the form, I often try to submit the form by pressing the Enter key in vain.
> Pressing Enter in the Domain entry of Auth dialog submits

- remmina/src/remmina_file.c
- remmina/src/remmina_file_editor.c
- remmina/src/remmina_protocol_widget.c
- remmina/src/remmina_sftp_plugin.c
- remmina/src/remmina_ssh.c
- remmina/src/remmina_ssh.h
- remmina/src/remmina_ssh_plugin.c
This PR fixes some general issues, introduces some improvements and fixes the following issues:
- #708 the checkbox, 'Save SSH Password',  grayed out.
- #1078 SSH password can't save , terminal auto disconnection
- #1187 "Public Key (Automatic)" option does not work with ed25519 keys 
Some enhancements require  libssh 0.7.X, i.e the support for ed25519 keys
> Ssh improvements

- remmina/src/remmina_file_editor.c
- remmina/src/remmina_sftp_plugin.c
- remmina/src/remmina_ssh.c
- remmina/src/remmina_ssh_plugin.c
This PR add additional improvements to the SSH plugin protocol, fix some bugs introduced by the previous PR #1196 and enables the SSH passphrase dialog box for the ssh_auth_publickkey_auto with emtpy password
> Ssh protocol plugin implementation

- remmina/src/remmina_icon.c
For Gnome Shell >= 3.16, we assume that GtkStatusIcon is visible on the drawer at the bottom left of the screen. So we do not quit remmina when all windows are closed and GtkStatusIcon is visible.
Fixes #1229
> Change Status Icon availability for gnome 3.16

- remmina/src/remmina_file_editor.c
This seems to fix the issue on being able to use the Enter key while in the Edit menu and password field is in focus.  Issue #1233.
> Enter key doesn't "Connect" when in Edit menu and password field is in focus  - #1233

- remmina/src/remmina_ssh_plugin.c
This set the Linux palette as the default color scheme.
> Set Linux as the default terminal color scheme. Fixes #1238

- remmina/src/remmina_ssh.c
Added ssh_agent in the list of authorized method, fixes #1228
It was an oversight.
> Added ssh_agent in the list of authorized method, fixes #1228

- remmina/src/remmina_ssh.c
Quick fix to close #1257
In the future I'll review entirely the sftp protocol.
> passphrase not yet used in sftp connection - closes #1257

- remmina-plugins/CMakeLists.txt
Note about zlib: I found no mentions of it elsewhere in the code, so it seems that it is only a dependency of LibVNCServer, not Remmina itself. Probably a holdover from when LibVNCServer was bundled with Remmina.
> Make building the VNC plugin optional

- remmina/src/remmina_file_editor.c
This patch ad a new "Save and Connect" button and improve the labeling of the others.
See issue #1247
> Better button labelling and new save button

- remmina-plugins/rdp/rdp_event.c
- remmina-plugins/rdp/rdp_plugin.c
- remmina-plugins/rdp/rdp_plugin.h
This patch upgrades the RDP settings "Use client keyboard mapping" by
- removing old legacy X11 code and replacing it with GTK3 code
- using TS_UNICODE_KEYBOARD_EVENT RDP message to send the server keystrokes already processed at the client side
This should fixes or help fixing issues #440 #1026 and #434
> RDP client keyboard mapping with GTK3

- remmina/desktop/remmina.desktop.in
As discussed with @giox069, this PR aims to fix a Debian lintian warning on the .desktop file.
Been harmless, merging the change upstream will allow me to drop the patchset on the Debian package completely.
> Add Keywords entry

- remmina/src/remmina_main.c
- remmina/src/remmina_pref.c
- remmina/src/remmina_pref.h
- remmina/src/remmina_pref_dialog.c
- remmina/src/remmina_pref_dialog.h
- remmina/src/remmina_ssh_plugin.c
- remmina/ui/remmina_preferences.glade
This PR implement the custom color scheme for SSH as requested in the issue #1235.
A default theme is loaded during the first remmina startup inside the remmina.pref file.
You can set a new scheme in different ways.
1. Using the import widget in the Remmina preferences dialog.
You can download Remmina color scheme files from https://github.com/mbadolato/iTerm2-Color-Schemes
2. Create one using the color editor in the Remmina preferences dialog
3. The geek way, editing the file ~/config/remmina/remmina.colors
With the following syntax:
```
[ssh_colors]
background = #d5ccba
cursor = #45373c
foreground = #45373c
color0 =  #20111b
color1 = #be100e
color2 = #858162
color3 = #eaa549
color4 = #426a79
color5 = #97522c
color6 = #989a9c
color7 = #968c83
color8 = #5e5252
color9 = #be100e
color10 = …
```
> Custom Color schemes for SSH

- remmina/src/remmina_connection_window.c
- remmina/src/remmina_pref.c
- remmina/src/remmina_pref_dialog.c
- remmina/src/remmina_pref_dialog.h
- remmina/src/remmina_ssh_plugin.c
- remmina/ui/remmina_preferences.glade
With @remminafan1 we have added a configurable shortcut to set the View-Only mode.
We have also fixed a bug in spice ( #1035 ) that was causing issues with this PR.
The shortcut is configurable from the preferences menu as usual.
> Shortcutkey viewonly

- remmina/src/remmina_connection_window.c
- remmina/src/remmina_pref.c
- remmina/src/remmina_pref.h
shortcutkey_viewonly - hardcoded Host+M - working
Patched 3 files to cause Host+M to toggle viewonly mode.
It has been very frustrating to have to move (local and remote) remote mouse pointer for the so frequent action "turn off viewonly, type / click as needed, turn on viewonly". Now it is extremely quicker to press Host+M, type / click as needed, Host+M. Patch is immediately functional, but to achieve release-grade quality, someone needs to add a button in the Preferences dialog -> Keyboard tab to customize the shortcut. (I tried but failed).
> shortcutkey_viewonly

- remmina/desktop/CMakeLists.txt
- remmina/desktop/remmina.appdata.xml
- remmina/src/remmina_connection_window.c
- remmina/src/remmina_public.c
- snap/CMakeLists.txt
I've a implemented a simple desktop notification that print the server name each time we enter a tab in the remmina connection window
It's not exactly what has been requested by @StuWhitby via #815 , but I think it's much better because it is the standard way advised by the Gnome project to notify the user, moreover the user can configure how, when and for how long the notifications are shown, without making things overcomplicated for Remmina.
@StuWhitby,  @giox069 what do you think? Later I'll add a couple of screenshot.
> Server name is notified to the user everytime we enter a tab

- remmina/src/remmina_connection_window.c
I've reverted the notification in favor the floating toolbar.
When you are in fullscreen (tabbed mode) and you switch between profiles, the floating toolbar temporary appears.
As there is the server name in the floating toolbar, we always now on which profile we are working on.
> Reverted the notfication for the floating toolbar

- remmina-plugins/vnc/vnc_plugin.c
Fix for issue #1300.
Please note that VNC is very limited in clipboard handling, and the only charset supported is latin-1 (ISO-8859-1), see [RFC6143 7.5.6](https://tools.ietf.org/html/rfc6143#section-7.5.6).
> Fix charset conversion in VNC clipboard

- snap/snapcraft.yaml.in
Use the new desktop, desktop-legacy and wayland interfaces introduced in snapd 2.28.  Also build freerdp with wayland support.  This fixes the
snap to work on Ubuntu Desktop 17.10 with the default session using
wayland.
> [snap] Use the new desktop, desktop-legacy and wayland interfaces

- CMakeLists.txt
- cmake/FindAPPINDICATOR.cmake
- remmina/src/remmina_icon.c
Canonical's appindicators have been recently forked in a new project, called [ayatana-appindicators](https://sunweavers.net/blog/node/58).
This patch allows cmake to find newest ayatana appindicators. Tested on Debian sid.
> Add support for ayatana-appindicators

- remmina/src/remmina_ssh.c
Empty passphrase should be a valid input for ssh_userauth_publickey_auto. Otherwise there is an extra passphrase dialog. It should appear only when ssh_userauth_publickey_auto really fails with empty passphrase.
> ssh_userauth_publickey_auto: should accept empty passphrase

- README.md
- remmina/src/remmina.1
- snap/snapcraft.yaml.in
Three files in the codebase present this typo.
This PR fixes it.
> Fix 'consistant' -> 'consistent' typo

- remmina-plugins/telepathy/CMakeLists.txt
- remmina-plugins/telepathy/org.freedesktop.Telepathy.Client.Remmina.service.in
- remmina-plugins/telepathy/telepathy_channel_handler.c
Lost during migration from autotools to cmake in commit 62ee2d0.
> telepathy: properly setup dbus activation

- remmina/CMakeLists.txt
- remmina/src/remmina_connection_window.c
- remmina/src/remmina_file_editor.c
- remmina/src/remmina_plugin_cmdexec.c
- remmina/src/remmina_protocol_widget.c
- remmina/src/remmina_utils.c
- remmina/src/remmina_utils.h
This PR is meant to improve the prior and post connection commands.
- Move prior command into remmina_protocol_widget_open_connection, fixes #1363
- Add niddles to set server name, tunnel server, username and ssh username as per #849
> Prior commands improvements

- flatpak/org.remmina.Remmina.json
Remmina uses some error definitions introduced on rev 2.0.0-rc1 of freerdp.
See commit: https://github.com/FreeRDP/FreeRDP/commit/7a73a0eb1b85d2e58402c45481058de013f68c43
> Updated freerdp on flatpak definition file

- flatpak/org.remmina.Remmina.json
- remmina/desktop/appdata.xml
- remmina/desktop/remmina.desktop.in
Update libraries to newer version.
Some improvements to adhere more to flathub guidelines.
(No specific modification for libsoup and json-glib as they are already present in gnome sdk)
> flatpak: update manifest file

- remmina/desktop/remmina.desktop.in
Even the xdmcp protocol is supported and this would avoid patching at distro-level (as Ubuntu is doing already).
> Add xdmcp protocol to Keywords

- remmina/src/remmina_ssh.c
- remmina/src/remmina_ssh.h
- remmina/src/remmina_ssh_plugin.c
Some SSH servers do not supports compression that is enabled by default.
This PR set it to default value that is "no".
I'll implement later an option to enable it if required
> Removed compression option as not compatible with all SSH servers

- plugins/telepathy/CMakeLists.txt
Fix compilation with -Wl,z,defs / -Wl,--no-undefined in CFLAGS.
Resolves #1432.
> telepathy: add dbus-glib-1 to link flags

- .travis.yml
- scripts/travis-build.sh
SNAP builds are now handled by https://build.snapcraft.io
Also remove publishing Travis build results to IRC channel
> Remove SNAP build from Travis

- plugins/vnc/CMakeLists.txt
- plugins/vnc/vnc_plugin.c
The VNCI plugin currently does not work, so we remove it from default builds. If you need to compile it, just add `-DWITH_VNCI=on` on cmake command line.
> Disable VNCI plugin

- remmina/src/remmina_about.c
Using Flathub Remmina package, I noticed the version string in Remmina's about dialog was truncated.
This commit aims to fix this.
> Don't truncate version string when building from a git tag

- cmake/FindAPPINDICATOR.cmake
- remmina/src/remmina_icon.c
Trailing libappindicator/ directory is not included in include path
returned by pkg-config (/usr/include/libappindicator3-0.1).
> build: make appindicator include consistent with pkg-config flags

- flatpak/Dockerfile
- flatpak/flatpak.sh
Current build issue seems to be triggered by a non-existent `/tmp` directory when the container is run.
For now, as a workaround, mount `/tmp` as a `tmpfs`.
The root reason for the missing `/tmp` should be investigated later.
> Fix travis flatpak build

- flatpak/Dockerfile
- flatpak/README.md
- flatpak/flatpak-build.sh
- flatpak/flatpak.sh
- scripts/travis-build.sh
Currently, travis flatpak build always uses the tip of next branch. This means builds triggered by a pull request does not test the changes introduced by the PR since the code is not merged in next branch yet.
This PR aims to fix this.
> travis: build flatpak using branch from PR instead of next

- plugins/rdp/CMakeLists.txt
- plugins/rdp/rdp_plugin.c
- plugins/rdp/rdp_settings.c
This patch autodetects when libfreerdp H264 support is missing (i.e. on OpenSuse or Ubuntu). This happens because these distributions cannot distribute libavcodec/libavutils/ffmpeg on the mian package archive area. When H264 support is not available from libfreerdp and a remmina user create a new profile which defaults to an GFX AVC mode, the user gets a warning asking him/her to use a different color Depth. But some user cannot understand that message, see issue #1584.
With this patch, when libfreerdp does not expose the libfreerdp cmake WITH_GFX_H264=ON build option, Remmina will automatically remove the two color depths "GFX AVC444" and "GFX AVC420" from the color depth dropdown in the profile editor, and fallback to "GFX RFX" mode when connecting if a profile is configured for one of …
> Autodetect missing H264 on libfreerdp

- plugins/rdp/rdp_file.c
- plugins/rdp/rdp_plugin.c
With these properties supported, Remmina can be used to launch RDP files generated by F5 APM.
> Support for "gatewayaccesstoken" (aka PAA) and "authentication level" RDP file properties

- cmake/FindAPPINDICATOR.cmake
- src/remmina_icon.c
@mfvescovi @larchunix @antenore 
This should reenable compilation with libayatana-appindicator after commit https://github.com/FreeRDP/Remmina/commit/a41cb9e0e90a69d18c4f9697fa271d9a0102aa93 broke it.
Tested on debian sid and Ubuntu 18.04.
> Fix ayatana libappindicator cmake search

- plugins/vnc/vnc_plugin.c
- src/remmina_file.c
Since ever REMMINA_PROTOCOL_SETTING_TYPE_KEYMAP setting name was not set.
It fixes #1642 
It should have the potential to solve other issues as the keymap value was not saved correctly.
> Fixing segmentation fault due to setting name NULL
