FreeRDP/Remmina

remmina-plugins/nx/nx_plugin.c
remmina-plugins/rdp/rdp_plugin.c
remmina-plugins/vnc/vnc_plugin.c
remmina-plugins/xdmcp/xdmcp_plugin.c
remmina/include/remmina/plugin.h
remmina/po/en_AU.po
remmina/po/en_GB.po
remmina/po/it.po
remmina/src/remmina_plugin_manager.c
remmina/src/remmina_protocol_widget.c
remmina/src/remmina_protocol_widget.h
remmina/src/remmina_public.c
remmina/src/remmina_public.h

This PR fixes the Issue #445 and offers a way to send keys to the server connections.
Added a feature to send Ctrl+Alt+Delete keys to VNC and RDP sessions.

Added feature to send Ctrl+Alt+Del keys

---

remmina/src/remmina_main.c

Can you please test it?
@muflone @giox069

Fixes FreeRDP/Remmina#460

---

remmina/ui/remmina_main.glade

Added Ctrl+F accelerator for quick search entry

---

remmina/po/en_AU.po
remmina/po/en_GB.po
remmina/po/it.po
remmina/src/remmina_pref.c
remmina/src/remmina_pref.h
remmina/src/remmina_pref_dialog.c
remmina/src/remmina_pref_dialog.h
remmina/ui/remmina_preferences.glade

Show or hide the icons near the buttons and the menus

---

remmina/src/remmina_applet_menu.c
remmina/src/remmina_external_tools.c
remmina/src/remmina_file.c
remmina/src/remmina_file_manager.c
remmina/src/remmina_pref.c

Added support for XDG folders structure, fixes #129 and  #197

Xdg folders fixes #129  #197 

---

remmina-plugins/vnc/vnc_plugin.c

Previous implelmentation used GDK pixbuf to store data.
It is very slow to draw pixbuf on cairo surface.
Using cairo surface improves performance

Improve vnc rendering speed by using cairo surface directly

---

remmina/src/remmina_connection_window.c
remmina/src/remmina_connection_window.h
remmina/src/remmina_file_editor.c
remmina/src/remmina_file_editor.h
remmina/src/remmina_ftp_client.c
remmina/src/remmina_ftp_client.h
remmina/src/remmina_init_dialog.c
remmina/src/remmina_init_dialog.h

Can you please tests with (reasonably) old GTK versions? 
This may impact:
- Connection editor
- (s)ftp interface
- main window
@giox069

Gtk3 -  Deprecation fixes

---

remmina-plugins/vnc/vnc_plugin.c

This patch add the format depth in the vnc client structure
closes #699

Vnc exit with 8bpp issue699

---

remmina-plugins/rdp/CMakeLists.txt

rdp-plugin requires x11 libraries

---

remmina/src/remmina_plugin_cmdexec.c

These change fixes a buffer-overflow introduced in #748

adjust lenght of strings

---

remmina-plugins/rdp/rdp_cliprdr.c

Maybe some additional stuff should be done in case there is insufficient space.

formats is not nulled upon failure

---

remmina/ui/remmina_main.glade

Added ctrl+f to Quick Search to supersed the standard GTK accelerator

---

remmina-plugins/vnc/vnc_plugin.c

This could potentially solves #681 #335

VNC - HandleRFBServerMessage return status

---

.github/ISSUE_TEMPLATE.md

Closes #822. Please merge if ok.

Added issue-template

---

remmina/po/uz@cyrillic.po

Commits 60488e71e75c8d6c86dbd8579baa2f1145f25e47 and 2164c1ccff2b85675891f416c256ac233b63350c made changes in msid's.
This reflects those changes to translation strings.

Update Uzbek translation

---

remmina/src/remmina_connection_window.c
remmina/src/remmina_file_editor.c
remmina/src/remmina_init_dialog.c
remmina/src/remmina_main.c
remmina/ui/remmina_about.glade
remmina/ui/remmina_main.glade

As reported by #817 positioning a window shouldn't be an application business, but it's the job of the Window Manager.
This PR should fix that particular issue and should improve the window manager interaction in general.
* closes #817 
* closes #829
TODO: I'm still working to improve the notebook managemt as it doesn't work with tiling window manager as GTK doesn't send the right WM hints.

WM hints and Window positioning

---

remmina/src/remmina_pref.c
remmina/src/remmina_pref.h
remmina/src/remmina_pref_dialog.c
remmina/src/remmina_pref_dialog.h
remmina/src/remmina_ssh_plugin.c
remmina/src/remmina_ssh_plugin.h
remmina/ui/remmina_preferences.glade

This PR add a popup menu to any SSH connection with the Copy, Paste and Select All commands.
Closes #833 
@giox069 , @weberhofer

Vte improvements - popup menu and terminal selection

---

remmina/src/remmina_file_editor.c

This PR makes the Server Name the default entry in the remmina_file_editor as requested by #838

Focus server box

---

remmina-plugins/spice/spice_plugin.c

This PR adds some improvements to the SPICE plugin:
- Fix a segfault triggered by double call to `spice_session_disconnect()`,
- Detect and report connection failure,
- Detect and report wrong connection password.
Regards.

SPICE plugin improvements

---

remmina-plugins/spice/spice_plugin.c

Hi,
Here are several improvements to the SPICE plugin:
- Raise a dialog window when the connection is closed by the server,
- Preference to disable clipboard sharing,
- Support for sending custom keystrokes.
Regards.

SPICE plugin improvements (again)

---

remmina-plugins/spice/spice_plugin.c

Also includes miscellaneous minor fixes.

Spice plugin: scaling support 

---

remmina-plugins/spice/spice_plugin.c

UnfortunateIy I don't have a smartcard reader to test this.
It would be good if a smartcard reader owner could try it :)

Spice plugin: smartcard redirection support

---

remmina/po/es.po

Translations ready

---

remmina-plugins/rdp/rdp_plugin.c
remmina/po/es.po
remmina/src/remmina_main.c
remmina/ui/remmina_about.glade
remmina/ui/remmina_main.glade

This PR closes #47 and #887.
#47 - Support opening rdp files (drag&drop)
#887 - No more keyboard shortcuts for quick search (+ focus on search bar by default)

Remmina main fixes

---

remmina/po/es.po

added \n in the credits
for next update

added \n in the credits

---

remmina/src/remmina_connection_window.c
remmina/src/remmina_connection_window.h
remmina/src/remmina_exec.c

Fixes #888.
Please review and test.

Don't quit Remmina if the user denies closing the connection window

---

remmina/src/remmina_main.c

Fix import label

---

remmina-plugins/spice/spice_plugin.c

Please review and test (http://www.spice-space.org/docs/manual/#_tls)

spice: add support for tls encrypted connections

---

cmake/GETTEXT.cmake

Commit 67a38b06132bf1b875ca0ab53b5477cce046da2e has a few mistakes (basically the lines inside the if are also duplicated outside, so they are always executed). I fixed that and made some small improvements.
Fixes #178

make gettext *really* behave correctly

---

remmina/src/remmina_file_editor.c

This PR should fix #263 , There are 4 commits but just one line modified.
@All  Please test if you can.
@Mystica555 can you please build and test this PR. Your help is much appreciated. thx
EDIT: I've squashed the commits.

Grab focus without selecting text in the remmina file editor

---

remmina-plugins/spice/spice_plugin_file_transfer.c

As discussed in #993. Feedback welcome.

spice: send a notification at the end of file transfers

---

remmina/po/fr.po

This is an up to date full French translation containing important fixes on misunderstanding (notably on what is the “host key”) and fixes on French typography rules.
Please, pull it.
Davy

Update French translation

---

remmina/src/remmina_connection_window.c

This is a possible fix for issue #146.
Currently in GTK when keyboard is captured via gdk_device_grab(), the application no longer receives "focus-out-event". This fix uses the "window-state-event" signal instead "focus-out-event" to detect focus loss.

Improves focus in/out detection when keyboard is captured

---

remmina/po/de.po

Added german translation for new message strings

updated german translation

---

remmina/src/remmina_public.c

Fixes workspace detection outside X11 backend.

---

remmina/po/es.po

Update Spanish Translation

---

remmina/src/remmina_file_editor.c

Fixed by @ppsshh through #1049

When 'Server' GtkComboBox is selected, TAB doesn't work

---

remmina-plugins/rdp/rdp_cliprdr.c
remmina-plugins/rdp/rdp_cliprdr.h
remmina-plugins/rdp/rdp_event.c
remmina-plugins/rdp/rdp_event.h
remmina-plugins/rdp/rdp_graphics.c
remmina-plugins/rdp/rdp_plugin.c
remmina-plugins/rdp/rdp_plugin.h
remmina/src/remmina_icon.c

With this PR Remmina is again in sync with FreeRDP master branch.

Libfreerdp updates

---

remmina-plugins/rdp/rdp_file.c

Should fix #1056
As it doesn't hurt, I'll merge this immediately after the build tests.

Import gateay values from rdp files - #1056

---

remmina/po/ru.po

@IgorFilth PLease comment on this. Do you think we can live with my mistakes or can we wait for a new Remmina release (at least 3/4 weeks)?
@nastasi @giox069 Should I submit a new release?

Fix russian translations as per #1070

---

remmina/src/remmina_connection_window.c

This should fix #124 if GTK version => 3.18
Please tests and let me know.

Make full screen in the same monitor where the connection window reside

---

remmina/src/remmina_connection_window.c

Still having problems under Gnome Shell under arch with GTK 3.22: keyboard is not captured.

Keyboard capture fixes, #1087 #1096 #1111

---

scripts/travis-build.sh
snap/snapcraft.yaml.in

snapcraft cmake repos build-type now reflects the cmake parameter

travis: build the snap for PRs in Debug mode

---

README.md

The buttons pointed to an invalid location previously

Inproved CodeTriage and Bountysource buttons

---

remmina-plugins/rdp/rdp_plugin.c

Now freerdp has better error handling. We no longer need to check if the server hostname exists: libfreerdp will take care of it and return us FREERDP_ERROR_DNS_NAME_NOT_FOUND if the host does not exists.

RDP: remove server hostname DNS check

---

remmina/src/remmina_ssh.c
remmina/src/remmina_ssh_plugin.c

This PR fixes and close #1076 and #1151

Terminal functionalities to make Remmina behave correctly with ncurses

---

CMakeLists.txt
remmina/src/remmina_file_editor.c
remmina/src/remmina_ssh.c
scripts/travis-build.sh
snap/snapcraft.yaml.in

- Fix Travis CI build
- Set SSH_OPTIONS_SSH_DIR in libssh and remove preload workaround
- Fix issue #1183 (was caused by preload workaround)

Fix snap issues

---

CONTRIBUTING.md

Just noticed the link for issue #376 was broken in CONTRIBUTING.md, here's the fix.

Fix link for issue #367

---

remmina/src/remmina_ssh_plugin.c

Fixed Linux, Tango and Xterm color schemes as reported by #1225

Fixed terminal color palettes

---

remmina/src/remmina_file_editor.c

This should fix the issue #1233
Please test it if the build passes.

Connect when pressing enter in the password field

---

remmina-plugins/rdp/rdp_event.c

Fixes some GTK warnings when scaler is enabled

Fix gtk redrawing in RDP plugin

---

remmina/src/remmina_icon.c

In gnome shell 3.26 the legacyTray (drawer) has been removed,
and there is no place where GtkStatusIcons will be shown.
See
- https://bugzilla.gnome.org/show_bug.cgi?id=785956
- https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/
In this case, remmina must exit when the main window is closed.
This undoes PR #1230, requested in issues #1236 and #1229

Exit strategy for Gnome Shell 3.26

---

.gitignore
remmina/src/remmina_pref.c
remmina/src/remmina_pref.h
remmina/src/remmina_pref_dialog.c
remmina/src/remmina_pref_dialog.h
remmina/src/remmina_public.c
remmina/ui/remmina_preferences.glade

- Update .gitignore
- Add a checkbox to make notifications optional

Fixes for notifications

---

remmina/src/remmina_file.c
remmina/src/remmina_file_editor.c

This PR should fix the bug reported by @Lonniebiz ( #1307 )
Unlucky I cannot test this till the next week.
Anybody willing to test it?

Make remmina_file_editor_on_save behave correcthly

---

remmina/src/remmina_pref_dialog.c
remmina/src/remmina_ssh_plugin.c

This should fix #1316 
Can you please test?

Add background and foreground colors for old versions of VTE

---

remmina/src/remmina_pref.c
remmina/src/remmina_pref_dialog.c

When I added this option it wasn't completely implemented.
Fixed

Un-check of 'Fullscreen on the same monitor'

---

remmina/po/zh_CN.po

update simplified Chinese translations.

update simplified Chinese translations.

---

.gitignore
flatpak/README.md
flatpak/org.remmina.Remmina.json

I have tested NX, SFTP, SPICE, SSH, VNC and XDMCP plugins and  I have not noticed major issues.
RDP basic functionalities (keyboard, video, mouse) work fine but I did not try advanced features.
Smart card support is not enabled for now (I don't have any smart card reader to test).
Please test and merge if interested.

flatpak: add manifest for flatpak-builder

---

remmina/src/remmina_file_editor.c
remmina/src/remmina_plugin_cmdexec.c
remmina/src/remmina_ssh.c
remmina/src/remmina_ssh_plugin.c
remmina/ui/remmina_spinner.glade

With this PR the SSH tunnel now works.
I've also improved a bit more the pre/post command, so that now, a user, can use it also to create more sophisticated tunnels with OpenSSH

SSH tunnel and pre/post commands improvements 

---

remmina/src/remmina_sftp_plugin.c

Align SFTP and SSH plugins authentication and tunnel functionalities. 

---

remmina-plugins/rdp/rdp_plugin.c
remmina/src/remmina_ssh.c
remmina/src/remmina_ssh.h
remmina/src/remmina_ssh_plugin.c

Partly improve issue described in #1374
@dmauz This PR should also include the tunnel fixes. I hope it works

 Added encryption algorithms options for SSH 

---

README.md

Added instructions for installation from Debian backports repository.

Updated README.MD with Debian install instructions

---

cmake/FindSPICE.cmake
flatpak/org.remmina.Remmina.json
remmina-plugins/nx/nx_plugin.c
remmina-plugins/spice/spice_plugin.c
remmina-plugins/telepathy/telepathy_handler.c

Implements #1273
Please test and merge if OK.

Add SPICE Native WebDAV shared folder support

---

remmina/po/fr.po

Ciao a tutti,
Here’s my updated French po file.
Freely yours,
Davy

Updated French po file

---

remmina/po/es_ve

More humane translations, different from es. po

New Spanish file venezuela

---

remmina-plugins/rdp/rdp_plugin.c
remmina/po/it.po

* Fixes certificate issue #1413
* Italian translations

Fixes 2017 christmas

---

Doxyfile
remmina-plugins/rdp/rdp_plugin.c
remmina-plugins/vnc/vnc_plugin.c
remmina/src/remmina_avahi.c
remmina/src/remmina_connection_window.c
remmina/src/remmina_file_editor.c
remmina/src/remmina_file_manager.c
remmina/src/remmina_main.c
remmina/src/remmina_plugin_manager.c
remmina/src/remmina_pref.c
remmina/src/remmina_protocol_widget.c
remmina/src/remmina_sftp_plugin.c
remmina/src/remmina_ssh.c
remmina/src/remmina_ssh_plugin.c

This should fix #1228 
I've also updated the documentation

Ssh tunnel fixes for #1228 

---

remmina/src/remmina_ssh.c

Please check if the return value is correct

Ensure the return value is initialized

---

remmina/src/remmina_stats.c
remmina/src/remmina_stats_sender.c
remmina/src/remmina_sysinfo.c
remmina/src/remmina_sysinfo.h
remmina/src/remmina_utils.c
remmina/src/remmina_utils.h

Remmina statistics.
- OS stats.
- Window manager stats.
- Code cleaning.
- More to come, you can leave opened this pull request.

OS stats and code cleaning

---

remmina-plugins/rdp/rdp_channels.c
remmina-plugins/rdp/rdp_event.c
remmina/src/remmina_connection_window.c

Permit SCALE_MODE_DYNRES before DISP_DVC_CHANNEL_NAME is enabled.

---

remmina-plugins/rdp/rdp_channels.c
remmina-plugins/rdp/rdp_event.c
remmina-plugins/rdp/rdp_plugin.c

Add support for [MS-RDPEGFX] (freerdp's /gfx: switch)
Fixes #1456 and #1449

Add initial [MS-RDPEGFX] software support

---

remmina/src/remmina_utils.c

Added Solus to the list of OSes for stat tracking.

Add OS info for Solus

---

remmina/desktop/appdata.xml
remmina/desktop/remmina-file.desktop.in

This should fix some issues reported by the Fedora users, like https://bugzilla.redhat.com/show_bug.cgi?id=1553098

Desktop data fixes

---

flatpak/org.remmina.Remmina.json

This should address the majority of the issues raised in https://github.com/flathub/flathub/pull/307

Update flatpak manifest according to feedback from Flathub

---

remmina/src/remmina_connection_window.c

Delay and use gtk_window_present_with_time()

---

remmina/src/remmina_file_editor.c
remmina/ui/remmina_main.glade

This is part of the Remmina refactoring

Redesign - Removed icons where not needed

---

remmina/src/remmina_pref.c
remmina/src/remmina_pref.h
remmina/src/remmina_pref_dialog.c
remmina/src/remmina_pref_dialog.h
remmina/src/remmina_ssh.c
remmina/ui/remmina_preferences.glade

Implemented 4 global options for these TCP parameters that are quite useful when connected to bad LNA/WAN connections.

TCP Socket parameters as global options. Closes #1487

---

flatpak/org.remmina.Remmina.json
flatpak/patches/libappindicator-ftbfs-gnome-sdk-3.28.patch

@antenore and/or @amtlib-dot-dll, could you build and test this ? If everything is fine you can also update flathub manifest.

Update Flatpak to GNOME SDK 3.28

---

flatpak/Dockerfile
remmina/src/remmina_pref_dialog.c
remmina/src/remmina_protocol_widget.c

This bump GTK requirement to GTK 3.2

GTK deprecation fixes

---

CMakeLists.txt

Useful to analyse some profiling metrics.

Clang LLVM coverage flags

---

plugins/spice/spice_plugin.c
remmina/src/remmina_ssh.c

SPICE: add support for ssh tunnelling

---

data/ui/remmina_main.glade

In some setup it's not possible anymore to drag the remmina main window. 
This should fix the problem

Headerbar spacing fixes

---

po/de.po

Don't think that this should really be a return-character

 Write newline instead of return 

---

data/ui/remmina_main.glade

Move search bar below the header. 

---

data/ui/remmina_main.glade

To improve issue reported in #1655

Add resize grip

---

data/ui/remmina_main.glade
src/remmina_main.c

How we were living without this feature????

Adding plugin column in the Remmina Main window
